config:
  LAG_BLOCKS: 3
  CHAIN: bitcoin
  PROVIDER_URI: http://rpcuser:rpcpassword@btc0-service.btc-0.svc.cluster.local:8332
  GCS_PREFIX: gs://<YOUR_BUCKET_HERE>/bitcoin-etl/streaming
  STREAM_OUTPUT: projects/<YOUR_PROJECT_HERE>/topics/crypto_bitcoin
  CHAIN_TYPE: bitcoin
stream:
  env:
    LAST_SYNCED_BLOCK_FILE_MAX_AGE_IN_SECONDS: "2400"
  livenessProbe:
    initialDelaySeconds: "1200"
    periodSeconds: "1200"
